cd ../postgres_bind_folder
mkdir pg_commit_ts
mkdir pg_dynshmem
mkdir pg_logical
mkdir pg_logical\mappings
mkdir pg_logical\snapshots
mkdir snapshots
mkdir pg_notify
mkdir pg_replslot
mkdir pg_serial
mkdir pg_snapshots
mkdir pg_stat_tmp
mkdir pg_tblspc
mkdir pg_twophase
mkdir pg_wal
mkdir pg_wal\archive_status
mkdir pg_wal\summaries